const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#canvas'),ctx=canvas.getContext('2d');
const cropCanvas=$('#cropCanvas'),cropCtx=cropCanvas.getContext('2d');
const state={photos:[],bg:'#f4ebdd',stampColor:'#f58fa5',stamps:[],cropIndex:-1,cropTemp:null,cropFrame:null,dragIndex:null};
const bgColors=['#F4EBDD','#F8F5EE','#DDD5C9','#E8D4D2','#D7E0E7','#D8E1D2','#DED8E8','#E3E3E3'];
const stampColors=['#F58FA5','#FF9E80','#F5B6D2','#C3A6E8','#91C9F7','#91D9C2','#F6D77A','#F3B27A'];
function colorPalette(el,colors,onPick){colors.forEach(c=>{const b=document.createElement('button');b.className='color-tile';b.style.background=c;b.title=c;b.onclick=()=>onPick(c);el.appendChild(b)})}
colorPalette($('#bgPalette'),bgColors,c=>{state.bg=c;$('#bgCustom').value=c;render()});
colorPalette($('#stampPalette'),stampColors,c=>{state.stampColor=c;$('#stampCustom').value=c});
$('#bgCustom').oninput=e=>{state.bg=e.target.value;render()};$('#stampCustom').oninput=e=>state.stampColor=e.target.value;
$$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));$$('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
$('#fileInput').onchange=async e=>{for(const f of e.target.files){if(!f.type.startsWith('image/'))continue;const url=URL.createObjectURL(f),img=await loadImage(url);state.photos.push({file:f,url,img,zoom:1,panX:0,panY:0})}e.target.value='';drawThumbs();render()};
function loadImage(src){return new Promise((ok,ng)=>{const i=new Image;i.onload=()=>ok(i);i.onerror=ng;i.src=src})}
function drawThumbs(){const box=$('#thumbs');box.innerHTML='';state.photos.forEach((p,i)=>{const d=document.createElement('div');d.className='thumb';d.draggable=true;d.innerHTML=`<img src="${p.url}"><div class="thumb-name">${p.file.name}</div><div class="thumb-actions"><span>${i+1}</span><button type="button">×</button></div>`;d.querySelector('img').onclick=()=>openCrop(i);d.querySelector('.thumb-name').onclick=()=>openCrop(i);d.querySelector('button').onclick=e=>{e.stopPropagation();URL.revokeObjectURL(p.url);state.photos.splice(i,1);drawThumbs();render()};d.ondragstart=()=>{state.dragIndex=i;d.classList.add('dragging')};d.ondragend=()=>d.classList.remove('dragging');d.ondragover=e=>e.preventDefault();d.ondrop=e=>{e.preventDefault();const from=state.dragIndex;if(from===null||from===i)return;const [m]=state.photos.splice(from,1);state.photos.splice(i,0,m);state.dragIndex=null;drawThumbs();render()};box.appendChild(d)})}
function slots(type,n){let a;if(type==='hero1')a=[[40,40,500,650,-.02],[570,60,460,300,.02],[585,390,420,300,-.02],[45,735,300,300,.02],[365,735,300,300,-.02],[685,735,330,300,.02],[55,1060,300,240,-.02],[380,1060,300,240,.02],[705,1060,300,240,-.02],[40,375,250,280,.03],[760,420,260,280,-.03],[400,1030,280,260,.01]];else if(type==='hero2')a=[[45,45,470,560,-.02],[565,45,470,560,.02],[45,645,310,310,-.02],[385,645,310,310,.02],[725,645,310,310,-.02],[45,980,310,300,.02],[385,980,310,300,-.02],[725,980,310,300,.02],[400,620,280,260,.01],[60,600,260,280,.03],[760,600,260,280,-.03],[400,1020,280,250,-.01]];else a=[[58,55,325,425,-.025],[382,40,330,420,.02],[724,70,300,408,.035],[55,455,330,390,-.025],[392,420,370,420,.018],[766,510,270,470,.025],[62,855,345,360,-.02],[414,845,338,365,.014],[735,995,290,270,.025],[35,300,260,300,.035],[760,260,290,310,-.035],[360,995,300,260,-.018]];return a.slice(0,n)}
function coverDraw(c,img,x,y,w,h,photo,border,shadow,angle){c.save();c.translate(x+w/2,y+h/2);c.rotate(angle);const bx=-w/2,by=-h/2;if(shadow){c.shadowColor='rgba(50,40,35,.25)';c.shadowBlur=18;c.shadowOffsetX=7;c.shadowOffsetY=9}c.fillStyle=border?'white':'transparent';c.fillRect(bx,by,w,h);c.shadowColor='transparent';const pad=border?12:0,iw=w-pad*2,ih=h-pad*2;const base=Math.max(iw/img.width,ih/img.height),scale=base*photo.zoom;const sw=iw/scale,sh=ih/scale;const overflowX=Math.max(0,img.width-sw),overflowY=Math.max(0,img.height-sh);const sx=overflowX*(photo.panX+1)/2,sy=overflowY*(photo.panY+1)/2;c.drawImage(img,sx,sy,sw,sh,bx+pad,by+pad,iw,ih);c.restore()}
function drawTape(c,x,y,a){c.save();c.translate(x,y);c.rotate(a);c.fillStyle='rgba(210,188,145,.72)';c.fillRect(-65,-12,130,24);c.restore()}
function drawTitle(){if(!$('#titleEnabled').checked)return;const text=$('#titleText').value.trim();if(!text)return;const font=$('#titleFont').value;ctx.save();ctx.translate(38,28);ctx.rotate(-.018);ctx.fillStyle='rgba(255,250,240,.94)';ctx.shadowColor='rgba(60,45,35,.16)';ctx.shadowBlur=10;ctx.shadowOffsetY=5;ctx.fillRect(0,0,450,82);ctx.shadowColor='transparent';ctx.fillStyle='#4f372b';ctx.font=`48px "${font}", sans-serif`;ctx.textBaseline='middle';ctx.fillText(text,24,43,400);ctx.restore()}
function drawSignature(){if(!$('#signatureEnabled').checked)return;const name=$('#profileName').value.trim(),xid=$('#profileXid').value.trim();if(!name&&!xid)return;const nameFont=$('#nameFont').value,xidFont=$('#xidFont').value;ctx.save();const boxW=330,boxH=104,x=canvas.width-boxW-34,y=canvas.height-boxH-28;ctx.fillStyle='rgba(255,250,240,.88)';ctx.shadowColor='rgba(60,45,35,.14)';ctx.shadowBlur=10;ctx.shadowOffsetY=5;ctx.fillRect(x,y,boxW,boxH);ctx.shadowColor='transparent';ctx.fillStyle='#4f372b';if(name){ctx.font=`40px "${nameFont}", sans-serif`;ctx.textAlign='right';ctx.fillText(name,x+boxW-20,y+45)}if(xid){ctx.font=`23px "${xidFont}", sans-serif`;ctx.fillText(xid,x+boxW-20,y+80)}ctx.strokeStyle='#ef8fa6';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x+135,y+90);ctx.lineTo(x+boxW-18,y+90);ctx.stroke();ctx.restore()}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle=state.bg;ctx.fillRect(0,0,canvas.width,canvas.height);const count=Math.max(0,Math.min(+$('#photoCount').value||8,state.photos.length,$('#textEnabled').checked?11:12));const selected=state.photos.slice(0,count);const total=selected.length+($('#textEnabled').checked?1:0);const s=slots($('#layout').value,total);selected.forEach((p,i)=>{const [x,y,w,h,a]=s[i];coverDraw(ctx,p.img,x,y,w,h,p,$('#border').checked,$('#shadow').checked,a);if($('#tape').checked&&[0,2,4,7].includes(i))drawTape(ctx,x+w*.45,y,a)});if($('#textEnabled').checked&&s[selected.length]){const [x,y,w,h,a]=s[selected.length];ctx.save();ctx.translate(x+w/2,y+h/2);ctx.rotate(a);if($('#shadow').checked){ctx.shadowColor='rgba(50,40,35,.2)';ctx.shadowBlur=18;ctx.shadowOffsetX=7;ctx.shadowOffsetY=9}ctx.fillStyle=$('#textBg').value;ctx.fillRect(-w/2,-h/2,w,h);ctx.shadowColor='transparent';ctx.fillStyle='#4f4138';ctx.font='bold 34px "Noto Sans JP", sans-serif';ctx.fillText($('#textHeading').value||'',-w/2+28,-h/2+55);ctx.font=`24px "${$('#commentFont').value}", sans-serif`;wrapText(ctx,$('#textBody').value,-w/2+28,-h/2+100,w-56,34);ctx.restore();if($('#tape').checked)drawTape(ctx,x+w*.45,y,a)}drawTitle();drawSignature();state.stamps.forEach(drawStamp)}
function wrapText(c,t,x,y,m,l){t.split('\n').forEach(p=>{let line='';for(const ch of p){const test=line+ch;if(c.measureText(test).width>m&&line){c.fillText(line,x,y);y+=l;line=ch}else line=test}c.fillText(line,x,y);y+=l})}
function drawStamp(s){const c=ctx,x=s.x,y=s.y,z=s.size;c.save();c.fillStyle=s.color;c.strokeStyle=s.color;c.lineWidth=Math.max(3,z/10);if(s.type==='heart'){c.beginPath();c.moveTo(x,y+z*.35);c.bezierCurveTo(x-z*.65,y-z*.1,x-z*.3,y-z*.65,x,y-z*.25);c.bezierCurveTo(x+z*.3,y-z*.65,x+z*.65,y-z*.1,x,y+z*.35);c.fill()}else if(s.type==='star'){c.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?z*.23:z*.5,px=x+Math.cos(a)*r,py=y+Math.sin(a)*r;i?c.lineTo(px,py):c.moveTo(px,py)}c.closePath();c.fill()}else if(s.type==='sparkle'){c.beginPath();c.moveTo(x,y-z/2);c.lineTo(x,y+z/2);c.moveTo(x-z/2,y);c.lineTo(x+z/2,y);c.stroke()}else{for(let i=0;i<6;i++){const a=i*Math.PI/3;c.beginPath();c.arc(x+Math.cos(a)*z*.25,y+Math.sin(a)*z*.25,z*.18,0,Math.PI*2);c.fill()}c.fillStyle='#f6d77a';c.beginPath();c.arc(x,y,z*.15,0,Math.PI*2);c.fill()}c.restore()}
$('#renderBtn').onclick=render;['layout','photoCount','border','shadow','tape','titleEnabled','titleText','titleFont','signatureEnabled','profileName','nameFont','profileXid','xidFont','textEnabled','textHeading','textBody','commentFont','textBg'].forEach(id=>$('#'+id).addEventListener('input',render));
canvas.onclick=e=>{if(!$('#stamp').classList.contains('active'))return;const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height;state.stamps.push({x,y,type:$('#stampType').value,size:+$('#stampSize').value,color:state.stampColor});render()};
$('#undoStamp').onclick=()=>{state.stamps.pop();render()};$('#clearStamps').onclick=()=>{state.stamps=[];render()};
function save(type){render();const a=document.createElement('a');a.download=`collage.${type==='image/png'?'png':'jpg'}`;a.href=canvas.toDataURL(type,.95);a.click()}$('#savePng').onclick=()=>save('image/png');$('#saveJpg').onclick=()=>save('image/jpeg');
let pointers=new Map(),lastDist=0,dragStart=null;
function getCropFrame(i){const photoCount=Math.max(1,Math.min(+$('#photoCount').value||8,state.photos.length,$('#textEnabled').checked?11:12));const total=photoCount+($('#textEnabled').checked?1:0);const allSlots=slots($('#layout').value,total);const fallback=slots('normal',12);const slot=allSlots[i]||fallback[Math.min(i,fallback.length-1)]||[0,0,325,425,0];return{w:slot[2],h:slot[3]}}
function openCrop(i){state.cropIndex=i;const p=state.photos[i];state.cropTemp={zoom:p.zoom,panX:p.panX,panY:p.panY};state.cropFrame=getCropFrame(i);$('#cropZoom').value=p.zoom;$('#cropDialog').showModal();drawCrop()}
function drawCrop(){const p=state.photos[state.cropIndex],t=state.cropTemp,f=state.cropFrame;if(!p||!t||!f)return;cropCtx.clearRect(0,0,cropCanvas.width,cropCanvas.height);cropCtx.fillStyle='#eee';cropCtx.fillRect(0,0,cropCanvas.width,cropCanvas.height);const margin=34,maxW=cropCanvas.width-margin*2,maxH=cropCanvas.height-margin*2,ratio=f.w/f.h;let w,h;if(maxW/maxH>ratio){h=maxH;w=h*ratio}else{w=maxW;h=w/ratio}const x=(cropCanvas.width-w)/2,y=(cropCanvas.height-h)/2;coverDraw(cropCtx,p.img,x,y,w,h,t,$('#border').checked,false,0)}
$('#cropZoom').oninput=e=>{state.cropTemp.zoom=+e.target.value;drawCrop()};
cropCanvas.onpointerdown=e=>{cropCanvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.offsetX,y:e.offsetY});if(pointers.size===1)dragStart={x:e.offsetX,y:e.offsetY,panX:state.cropTemp.panX,panY:state.cropTemp.panY};if(pointers.size===2){const a=[...pointers.values()];lastDist=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)}};
cropCanvas.onpointermove=e=>{if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.offsetX,y:e.offsetY});if(pointers.size===1&&dragStart){state.cropTemp.panX=Math.max(-1,Math.min(1,dragStart.panX-(e.offsetX-dragStart.x)/150));state.cropTemp.panY=Math.max(-1,Math.min(1,dragStart.panY-(e.offsetY-dragStart.y)/180));drawCrop()}else if(pointers.size===2){const a=[...pointers.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);state.cropTemp.zoom=Math.max(1,Math.min(3,state.cropTemp.zoom+(d-lastDist)/180));lastDist=d;$('#cropZoom').value=state.cropTemp.zoom;drawCrop()}};
function endPointer(e){pointers.delete(e.pointerId);if(!pointers.size)dragStart=null}cropCanvas.onpointerup=endPointer;cropCanvas.onpointercancel=endPointer;cropCanvas.onwheel=e=>{e.preventDefault();state.cropTemp.zoom=Math.max(1,Math.min(3,state.cropTemp.zoom+(e.deltaY<0?.08:-.08)));$('#cropZoom').value=state.cropTemp.zoom;drawCrop()};
$('#cropReset').onclick=()=>{state.cropTemp={zoom:1,panX:0,panY:0};$('#cropZoom').value=1;drawCrop()};$('#cropApply').onclick=()=>{Object.assign(state.photos[state.cropIndex],state.cropTemp);$('#cropDialog').close();render()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');document.fonts.ready.then(render);render();
